# -*- coding: utf-8 -*-
"""lab_assignment_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EQzpReZJTzyEeItyLHe8AS2v4NtJ-eHB

**Task 1 (a)**
"""

x= 24

while x>=-6:
    
    if x== -6:
        print(x)

    else:
        print(x, end=", ")
        
    x-=6

"""**Task 1 (b)**"""

x= -10

while x<=20:
    
    if x== 20:
        print(x)

    else:
        print(x, end=", ")
        
    x+= 5

# print(x-y*(x//y)) [Mod for negative]
# print(-3-4*(-3//4))

"""**Task 1 (c)**"""

x= 18

while x<=63:
    
    if x== 63:
        print(x)

    else:
        print(x, end=", ")
        
    x+= 9

"""**Task 1 (d)**"""

x= 18

while x<=63:   
    if x%2!=0:
        if x== 63:
            print(x*(-1), end="")
        else:
            print(x*(-1), end=", ")
    else:
        print(x, end=", ")
        
    x+=9

"""**Task 2**"""

favorite_car = str(input())
number = int(input())

for i in range(number):
    print(favorite_car)

"""**Task 3**"""

sum=0

for i in range(0, 601, 1):
    if i%7==0 and i%9==0:
        sum+=i

print(sum)

"""**Task 4**"""

sum=0

for i in range(0, 601,1):

    if i%7==0 and i%9==0:
        continue

    elif i%7==0 or i%9==0:
        sum+=i

print(sum)

"""**Task 5**"""

for i in range(10, 51, 1):
    if i%2!=0:
        print(i, end=(" "))

"""**Task 6**"""

n= int(input())

sum=0

for i in range(0, n+1, 1):
    if (i%2==0):
        sum-=i*i
    else:
        sum+=i*i

print (sum)

"""**Task 7**"""

sum=0
total=0
count=1

while count<=10:
    x=int(input())
    count+=1

    if x%2!=0:
        sum+=x
        total+=1

      
print (float(sum/total))

"""**Task 8**"""

N= int(input())
sum=0

for i in range(7, N+1, 7):
    sum+=i

print (sum)

"""**Task 9**"""

sum=0

for i in range(1, 6, 1):
    x=int(input())
    sum+=x
    print(sum)

"""**Task 10**"""

x=int(input())

while x>0:
    sum=x%10 #8
    x=x//10  #3276

    if x==0:
        print(sum,end="")
    else:
        print(sum,end=", ")

"""**Task 11**"""

x= int(input())
count=0

while x>0:
    x=x//10
    count+=1

print(count)

"""**Task 12**"""

x=int(input())
x1=x
count=0

while x!=0:
    x=x//10
    count+=1

count-=1 #4

sum= 10**count #10000

while x1>0: #True
    sum1=x1//sum # sum1= 32768//10000 = 3
    x1=x1%sum     # x= 32768 % 10000 = 2768
    sum=sum//10 # sum= 10000//10 = 1000

    if x1==0:
        print(sum1,end="")
    else:
        print(sum1,end=", ")

"""**Task 13**"""

x= int(input())
counter=0

for i in range(1, x+1, 1):
    if x%i==0:
        print(i)
        counter+=1

print("Total",counter,"divisors.")

"""**Task 14**"""

x= int(input())
sum=0

for i in range(1, x, 1):
    if x%i==0:
        sum+=i
    
if sum==x:      
    print(x, "is a perfect number")
else:
    print(x,"is not a perfect number")

"""**Task 15**"""

x= int(input())
counter=0

for i in range(1, x+1, 1):
    if x%i==0:
        counter+=1
    
if counter==2:      
    print(x, "is a prime number")
else:
    print(x,"is not a prime number")

"""**Task 16**"""

num_inputs=int(input())
total=0
count=0
max_num=float('-inf')
min_num=float('inf')

for i in range(1, num_inputs+1, 1):
    num=int(input())
    total+=num
    count+=1

    if num> max_num:
        max_num = num
    if num< min_num:
        min_num = num

if count > 0:
    
    average= float(total/num_inputs)

    print ("Maximum", max_num)
    print ("Minimum", min_num)
    print ("Average is",average)

"""**Task 17**"""

num= int(input())

for i in range(1, num+1, 1):
    for i in range(1, num+1, 1):
        print("+",end="")
    print()

"""**Task 18**"""

M= int(input())
N= int(input())

for i in range(1, M+1, 1):
    for i in range(1, N+1, 1):
        print(i, end="")
    print()

"""**Task 19**"""

N= int(input())

for m in range(1, N+1, 1):
    for i in range(1, m+1, 1):
        print(i, end="")
    print()

"""**Task 26**"""

decimal_number=int(input()) #13
binary_number = ""


while decimal_number>0:
    remainder=decimal_number%2
    decimal_number=decimal_number//2
    binary_number= str(remainder) + binary_number
  # binary_number(1)= "1" + ""  
  # binary_number(01)= "0" + "1"  
  # binary_number(101)= "1" + "01"  
  # binary_number(11011)= "1" + "101"  

print(binary_number if binary_number != "" else "0")