# -*- coding: utf-8 -*-
"""lab_assignment_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ahvGbOUeXTjBvYiKp0r8dQ64A5gc9xh9

**Task 1**
"""

x= int(input())
y= int(input())

sum= x+y
product=x*y
difference=x-y

print("Sum=",sum)
print("Product=",product)
print("Difference=",difference)

"""**Task 2**"""

import math
radius= float(input())
area= float( math.pi * pow(radius,2))
circumference= float( 2* math.pi *radius)
print("Area is",area)
print("Circumference is", circumference)

"""**Task 3**"""

x= float(input())
y= float(input())

if x>y:
    print ("First is greater")

elif x<y:
    print ("Second is greater")

else:
    print ("The numbers are equal")

"""**Task 4**"""

x= int (input())
y= int (input())

if x>y:
    print (x-y)

elif x<y:
    print (y-x)

else:
    print (x-y)

"""**Task 5**"""

number= int(input())

if number%2==0:
    print("The number is even")

else:
    print("The number is odd")

"""**Task 6**"""

x= int(input())

if x%2==0 or x%5==0:
    print (x)

else: 
    print ("Not a multiple of 2 OR 5")

"""**Task 7**"""

x= int(input())

if (x%2==0 and x%5==0):
    print ("Multiple of 2 and 5 both")

elif (x%2==0 or x%5==0):
    print (x)

else:
    print ("Not a multiple we want")

"""**Task 8**"""

x= int(input())

if (x%2==0 and x%5==0):
    print (x)

else:
    print ("Not multiple of 2 and 5 both")

"""**Task 9**"""

number_of_seconds= int(input())

if number_of_seconds>=3600:
    hour= number_of_seconds//3600
    number_of_seconds-=hour*3600
else:
    hour=0

if number_of_seconds <3600 and number_of_seconds >=60:
    mins= number_of_seconds//60
    number_of_seconds-=mins*60
else:
    mins=0

if number_of_seconds <60:
    seconds= number_of_seconds
else:
    second=0

print ("Hours:",hour,"Minutes:",mins,"Seconds:",seconds)

"""**Task 10**"""

hours = int(input())

if hours<0 :
    print ("Hour cannot be negative")

elif hours>168:
    print ("Impossible to work more than 168 hours weekly")

elif hours<=40 :
    print (hours*200)

elif hours>40:
    print (8000 + 300*(hours-40))

"""**Task 11**"""

import math

S= int(input())

if S<100:
    L= (3000-125*(math.pow(S,2)))
    print(float(L))
elif S>=100:
    L= (12000/(4+((math.pow(S,2))/14900)))
    print(float(L))

"""**Task 12**"""

hour= int(input())
  
if hour>=4 and hour<=6:
    print ("Breakfast")

elif hour>=12 and hour<=13:
    print ("Lunch")

elif hour>=16 and hour<=17:
    print ("Snacks")

elif hour>=19 and hour<=20:
    print ("Dinner")

elif hour<0 or hour>23:
    print ("Wrong time")

else:
    print("Patience is a virtue")

"""**Task 13**"""

number= int(input())

if number<50 and number>=0:
    print ("F")

elif number<=59 and number>=50:
    print ("E")

elif number<=69 and number>=60:
    print ("D") 

elif number<=79 and number>=70:
    print ("C")

elif number<=89 and number>=80:
    print ("B")

elif number<=100 and number>=90:
    print ("A")
   
else:
    print("The mark is invalid")

"""**Task 14**"""

distance_meters= int(input())
time_seconds= int(input())

distance_km= (distance_meters/1000)
time_hour= (time_seconds/3600)

velocity= distance_km/time_hour


if velocity<60:
    print (velocity,"km/h\n"+"Too slow. Needs more changes.")

elif velocity>=60 and velocity<=90:
    print (velocity,"km/h\n"+"Velocity is okay. The car is ready!")

elif velocity>90:
    print (velocity,"km/h\n"+"Too fast. Only a few changes should suffice.")

"""**Task 15**"""

CGPA=  float (input())
credits= int(input())

if CGPA>=3.80 and CGPA<=3.89 and credits>=30:
    print ("The student is eligible for a waiver of 25 percent.")
elif CGPA>=3.90 and CGPA<=3.94 and credits>=30:
    print ("The student is eligible for a waiver of 50 percent.")
elif CGPA>=3.95 and CGPA<=3.99 and credits>=30:
    print ("The student is eligible for a waiver of 75 percent.")
elif CGPA==4.00 and credits>=30:
    print ("The student is eligible for a waiver of 100 percent.")

else:
    print ("The student is not eligible for a waiver")

"""***Task 16***"""

p = 5
q = 6
r = 9
sum = 0
if (p < 12):
    print(r + 2)
else:
    print(r + p)
if (q > 20):
    print(r + 19)
elif (q <= 6):
    print(q + 3)
else:
    print(p + q + r)
if (r > 15):
    print(r)
elif (r == 0):
    print(p + q)
else:
    print(p)
if (sum != 0):
    print(3)
else:
    print(sum + 32)
if (p>0 and r<10):
    print(p+r)
else:
    print(p-r)

"""***Task 17***"""

var1 = var2 = var3 = var4 = var5 = var6 = False
result1 = False
result2 = False
result3 = False
result4 = False
result5 = False
result6 = False
result7 = False
result8 = False
result9 = False
result10 = False
var1 = 4 > 3 - 1
var2 = var1 and False
var3 = True
var4 = False
var5 = True
var6 = var3 and False
result1 = (var1 or var2) and (8 * 10 > 45)
result2 = (var1 or var2) and (result1 and False)
result3 = (var1 and result1) or result2
result4 = (var1 or var2) or ((var3 and var1) and False)
result5 = (var1 and var2) and (result3 or var1)
result6 = ((var3 or var2) and not(result5)) or True
result7 = (var4 and result1) and ((result1 and False) or True)
result8 = ((var1 and result3) and (var5 or var6)) and True
result9 = ((result2 and var2) or (result7 and var1)) and False
result10 = not(var1 and True)

print (result1,result2,result3,result4,result5,result7,result8,result9,result10)

"""***Task 18***"""

var1 = False
var2 = False
var3 = False
var4 = False
var5 = False
var6 = False
result1 = False
result2 = False
result3 = False
result4 = False
result5 = False
result6 = False
result7 = False
result8 = False
result9 = False
result10 = False
var1 = ((not True) or True) and False
var2 = var1 and False
var3 = True and not False
var4 = False
var5 = True
var6 = var3 and False
result1 = (var1 and var2) and (40 % 3) > 45 or (var5 and var6)
result2 = (var1 or var2) or (result1 and False)
result3 = (var1 and result1) or result2 or var5
result4 = (var1 or var2) or ((var3 and var1) and False)
result5 = (var1 and var2) and (result3 or var1)
result6 = ((var3 or (not var2)) and (result5)) or True
result7 = (var4 and result1) and ((result1 and False) or True)
result8 = ((var1 and result3) and ((not var5) or var6)) and True
result9 = ((result2 and var2) or ((not result7) and var1)) and not False
result10 = not(var1 and True)

print (result1,result2,result3,result4,result5,result7,result8,result9,result10)

"""**Task 20**"""

x= int(input())

if (x%2==0 or x%5==0)==False:
    print(x)

else:
    print("No")

"""**Task 21**"""

x= int(input())

if (x%2!=0 or x%5!=0):
    print(x)
else:
    print("No")

"""**Task 22**"""

canvas=int(input())
paint_tube=int(input())

canvas_price= 120
paint_tube_price= 75


total_price= int(canvas*canvas_price + paint_tube*paint_tube_price)

if total_price>=0 and total_price<=299:
    
    after_discount=int(total_price-0)
    print("Previous total:", total_price)
    print("New total after discount:",after_discount)

elif total_price>=300 and total_price<=499:

    after_discount=int(total_price-10)
    print("Previous total:",total_price)
    print("New total after discount:",after_discount)

elif total_price>=500 and total_price<=749:
    
    after_discount=int(total_price-20)
    print("Previous total:",total_price)
    print("New total after discount:",after_discount)

elif total_price>=750 and total_price<=999:
    
    after_discount=int(total_price-50)
    print("Previous total:",total_price)
    print("New total after discount:",after_discount)

elif total_price>=1000:
    
    after_discount=int(total_price-150)
    print("Previous total:",total_price)
    print("New total after discount:",after_discount)

"""**Task 23**"""

degrees_fahrenheit= int(input())

degrees_celsius= float((degrees_fahrenheit-32)*0.56)

if degrees_celsius<20:
    print ("%.2f" % degrees_celsius, "degrees C")
    print("Winter")
elif degrees_celsius>20 and degrees_celsius<=25:
    print ("%.2f" % degrees_celsius, "degrees C")
    print("Autumn")
elif degrees_celsius>25 and degrees_celsius<30:
    print ("%.2f" % degrees_celsius, "degrees C")
    print("Spring")
elif degrees_celsius>=30:
    print ("%.2f" % degrees_celsius, "degrees C")
    print("Summer")