# -*- coding: utf-8 -*-
"""lab_assignment_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1alTaoqd0u4xSbbwUID4tRrA9N-uSDw0u

**Task 1**
"""

print("hello world")

"""**Task 2**

"""

print (54+56)

"""**Task 3**

"""

season= "Fall"
year= 2022

print (season)
print (year)

"""**Task 4**



"""

name = input ()
print ("Your name is" ,name)

"""**Task 5**

"""

M= int (input ())
N= int (input ())

sum= M**N
print (M,"^",N,":",sum)

"""**Task 6**"""

M=int(input())

print(M-(M%4))

"""**Task 7**"""

A = int (input())
B = int (input())
C = int (input())
D = float(input())

print (int(A**C+B*A-(D/3)))

"""**Task 8**"""

number_of_chocolates = int(input())
sum= int(number_of_chocolates/3)
remaining_chocolates = int (number_of_chocolates-(sum*3))

print ("Each friend will receive",sum,"chocolates")

print ("The number of remaining chocolates is",remaining_chocolates)

"""**Task 9**"""

M= input()
N= input()

print(N+M)

"""**Task 10**"""

line= input()
print(line[0])

"""**Task 11**"""

x= int(input())
sum =int(x%2)
if sum==0:
  print("True")

else:
  print("False")

x= int(input())
print (bool(x%2==0))